name: Build and Deploy to Tomcat

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: master
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build WAR with Maven
        run: mvn clean package

      - name: Copy WAR to remote Tomcat
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.war"
          target: "/opt/apache-tomcat-11.0.5/webapps"

      - name: Restart Tomcat service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: /opt/apache-tomcat-11.0.5/bin/shutdown.sh; /opt/apache-tomcat-11.0.5/bin/startup.sh
